/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION

SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON

COMMIT

BEGIN TRANSACTION
GO

CREATE TABLE dbo.Tmp_CLIENTES (
    ID BIGINT NOT NULL IDENTITY(1, 1)
    , NOME VARCHAR(50) NOT NULL
    , SOBRENOME VARCHAR(255) NOT NULL
    , NACIONALIDADE VARCHAR(50) NOT NULL
    , CPF VARCHAR(11) NOT NULL
    , EMAIL VARCHAR(2079) NULL
    , TELEFONE VARCHAR(15) NULL
    , CEP VARCHAR(9) NOT NULL
    , CIDADE VARCHAR(50) NOT NULL
    , ESTADO VARCHAR(2) NOT NULL
    , LOGRADOURO VARCHAR(500) NOT NULL
    ) ON [PRIMARY]
GO

ALTER TABLE dbo.Tmp_CLIENTES

SET (LOCK_ESCALATION = TABLE)
GO

SET IDENTITY_INSERT dbo.Tmp_CLIENTES ON
GO

IF EXISTS (
        SELECT *
        FROM dbo.CLIENTES
        )
    EXEC (
            'INSERT INTO dbo.Tmp_CLIENTES (ID, NOME, SOBRENOME, NACIONALIDADE, EMAIL, TELEFONE, CEP, CIDADE, ESTADO, LOGRADOURO)
		SELECT ID, NOME, SOBRENOME, NACIONALIDADE, EMAIL, TELEFONE, CEP, CIDADE, ESTADO, LOGRADOURO FROM dbo.CLIENTES WITH (HOLDLOCK TABLOCKX)'
            )
GO

SET IDENTITY_INSERT dbo.Tmp_CLIENTES OFF
GO

DROP TABLE dbo.CLIENTES
GO

EXECUTE sp_rename N'dbo.Tmp_CLIENTES'
    , N'CLIENTES'
    , 'OBJECT'
GO

ALTER TABLE dbo.CLIENTES ADD CONSTRAINT PK__CLIENTES__3214EC2728120D5D PRIMARY KEY CLUSTERED (ID)
    WITH (
            STATISTICS_NORECOMPUTE = OFF
            , IGNORE_DUP_KEY = OFF
            , ALLOW_ROW_LOCKS = ON
            , ALLOW_PAGE_LOCKS = ON
            ) ON [PRIMARY]
GO

ALTER TABLE dbo.CLIENTES ADD CONSTRAINT IX_CLIENTES_CPF UNIQUE NONCLUSTERED (CPF)
    WITH (
            STATISTICS_NORECOMPUTE = OFF
            , IGNORE_DUP_KEY = OFF
            , ALLOW_ROW_LOCKS = ON
            , ALLOW_PAGE_LOCKS = ON
            ) ON [PRIMARY]
GO

COMMIT
