SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROC [dbo].[FI_SP_AltCliente] @ID BIGINT
    , @NOME VARCHAR(50)
    , @SOBRENOME VARCHAR(255)
    , @NACIONALIDADE VARCHAR(50)
    , @CPF VARCHAR(11)
    , @EMAIL VARCHAR(2079)
    , @TELEFONE VARCHAR(15)
    , @CEP VARCHAR(9)
    , @ESTADO VARCHAR(2)
    , @CIDADE VARCHAR(50)
    , @LOGRADOURO VARCHAR(500)
AS
BEGIN
    UPDATE CLIENTES
    SET NOME = @NOME
        , SOBRENOME = @SOBRENOME
        , NACIONALIDADE = @NACIONALIDADE
        , CPF = @CPF
        , EMAIL = @EMAIL
        , TELEFONE = @TELEFONE
        , CEP = @CEP
        , ESTADO = @ESTADO
        , CIDADE = @CIDADE
        , LOGRADOURO = @LOGRADOURO
    WHERE Id = @Id
END
GO