SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE FI_SP_ConsBenef @ID BIGINT = NULL
    , @IDCLIENTE BIGINT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    SELECT [ID]
        , [CPF]
        , [NOME]
        , [IDCLIENTE]
    FROM [dbo].[BENEFICIARIOS] WITH (NOLOCK)
    WHERE ISNULL(@ID, ID) = ID
        AND ISNULL(@IDCLIENTE, IDCLIENTE) = IDCLIENTE
    ORDER BY NOME
END
GO


